/* automatically generated from keyboard-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (keyboard_dialog_glade)
#endif
#ifdef __GNUC__
static const char keyboard_dialog_glade[] __attribute__ ((__aligned__ (4))) =
#else
static const char keyboard_dialog_glade[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><!DOCTYPE g"
  "lade-interface SYSTEM \"glade-2.0.dtd\"><glade-interface><requires lib="
  "\"xfce4\"/><widget class=\"XfceTitledDialog\" id=\"keyboard-settings-di"
  "alog\"><property name=\"title\" translatable=\"yes\">Keyboard Settings<"
  "/property><property name=\"window_position\">GTK_WIN_POS_CENTER_ON_PARE"
  "NT</property><property name=\"default_width\">400</property><property n"
  "ame=\"icon_name\">preferences-desktop-keyboard</property><property name"
  "=\"type_hint\">GDK_WINDOW_TYPE_HINT_DIALOG</property><property name=\"h"
  "as_separator\">False</property><property name=\"subtitle\" translatable"
  "=\"yes\">Keyboard settings and shortcuts</property><child internal-chil"
  "d=\"vbox\"><widget class=\"GtkVBox\" id=\"dialog-vbox1\"><property name"
  "=\"visible\">True</property><property name=\"spacing\">2</property><chi"
  "ld><widget class=\"GtkVBox\" id=\"plug-child\"><property name=\"visible"
  "\">True</property><property name=\"border_width\">6</property><property"
  " name=\"spacing\">6</property><child><widget class=\"GtkNotebook\" id=\""
  "notebook1\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><child><widget class=\"GtkVBox\" id=\"vbox2\""
  "><property name=\"visible\">True</property><property name=\"border_widt"
  "h\">12</property><property name=\"spacing\">6</property><child><widget "
  "class=\"GtkVBox\" id=\"vbox3\"><property name=\"visible\">True</propert"
  "y><property name=\"spacing\">6</property><child><widget class=\"GtkFram"
  "e\" id=\"frame2\"><property name=\"visible\">True</property><property n"
  "ame=\"label_xalign\">0</property><property name=\"shadow_type\">GTK_SHA"
  "DOW_NONE</property><child><widget class=\"GtkAlignment\" id=\"alignment"
  "2\"><property name=\"visible\">True</property><property name=\"bottom_p"
  "adding\">6</property><property name=\"left_padding\">12</property><chil"
  "d><widget class=\"GtkVBox\" id=\"vbox3\"><property name=\"visible\">Tru"
  "e</property><property name=\"border_width\">6</property><property name="
  "\"spacing\">6</property><child><widget class=\"GtkCheckButton\" id=\"xk"
  "b_key_repeat_check\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"tooltip\" translat"
  "able=\"yes\">When enabled, pressing and holding down a key emits the sa"
  "me character over and over again</property><property name=\"label\" tra"
  "nslatable=\"yes\">_Enable key repeat</property><property name=\"use_und"
  "erline\">True</property><property name=\"response_id\">0</property><pro"
  "perty name=\"active\">True</property><property name=\"draw_indicator\">"
  "True</property></widget><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">False</property></packing></child><child><w"
  "idget class=\"GtkAlignment\" id=\"xkb_key_repeat_box\"><property name=\""
  "visible\">True</property><property name=\"left_padding\">12</property><"
  "child><widget class=\"GtkVBox\" id=\"vbox6\"><property name=\"visible\""
  ">True</property><property name=\"spacing\">6</property><child><widget c"
  "lass=\"GtkLabel\" id=\"label7\"><property name=\"visible\">True</proper"
  "ty><property name=\"xalign\">0</property><property name=\"label\" trans"
  "latable=\"yes\">_Repeat delay:</property><property name=\"use_underline"
  "\">True</property><property name=\"mnemonic_widget\">xkb_key_repeat_del"
  "ay_scale</property></widget><packing><property name=\"expand\">False</p"
  "roperty><property name=\"fill\">False</property></packing></child><chil"
  "d><widget class=\"GtkHScale\" id=\"xkb_key_repeat_delay_scale\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"tooltip\" translatable=\"yes\">The time in mil"
  "liseconds before a pressed key starts repeating</property><property nam"
  "e=\"update_policy\">GTK_UPDATE_DELAYED</property><property name=\"adjus"
  "tment\">500 10 1000 1 10 1</property><property name=\"digits\">0</prope"
  "rty><property name=\"value_pos\">GTK_POS_RIGHT</property></widget><pack"
  "ing><property name=\"position\">1</property></packing></child><child><w"
  "idget class=\"GtkLabel\" id=\"label10\"><property name=\"visible\">True"
  "</property><property name=\"xalign\">0</property><property name=\"label"
  "\" translatable=\"yes\">Repeat _speed:</property><property name=\"use_u"
  "nderline\">True</property><property name=\"mnemonic_widget\">xkb_key_re"
  "peat_rate_scale</property></widget><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">False</property><property name=\""
  "position\">2</property></packing></child><child><widget class=\"GtkHSca"
  "le\" id=\"xkb_key_repeat_rate_scale\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"t"
  "ooltip\" translatable=\"yes\">The rate at which keycodes are generated "
  "while a key is pressed</property><property name=\"update_policy\">GTK_U"
  "PDATE_DELAYED</property><property name=\"adjustment\">20 1 250 1 10 1</"
  "property><property name=\"digits\">0</property><property name=\"value_p"
  "os\">GTK_POS_RIGHT</property></widget><packing><property name=\"positio"
  "n\">3</property></packing></child></widget></child></widget><packing><p"
  "roperty name=\"position\">1</property></packing></child></widget></chil"
  "d></widget></child><child><widget class=\"GtkLabel\" id=\"label5\"><pro"
  "perty name=\"visible\">True</property><property name=\"label\" translat"
  "able=\"yes\">&lt;b&gt;Typing Settings&lt;/b&gt;</property><property nam"
  "e=\"use_markup\">True</property></widget><packing><property name=\"type"
  "\">label_item</property></packing></child></widget><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">False</property>"
  "</packing></child><child><widget class=\"GtkFrame\" id=\"frame3\"><prop"
  "erty name=\"visible\">True</property><property name=\"label_xalign\">0<"
  "/property><property name=\"shadow_type\">GTK_SHADOW_NONE</property><chi"
  "ld><widget class=\"GtkAlignment\" id=\"alignment3\"><property name=\"vi"
  "sible\">True</property><property name=\"left_padding\">12</property><ch"
  "ild><widget class=\"GtkVBox\" id=\"vbox4\"><property name=\"visible\">T"
  "rue</property><property name=\"border_width\">6</property><property nam"
  "e=\"spacing\">6</property><child><widget class=\"GtkCheckButton\" id=\""
  "net_cursor_blink_check\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">True</property><property name=\"label\" transl"
  "atable=\"yes\">Show _blinking</property><property name=\"use_underline\""
  ">True</property><property name=\"response_id\">0</property><property na"
  "me=\"draw_indicator\">True</property></widget><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property></pack"
  "ing></child><child><widget class=\"GtkAlignment\" id=\"net_cursor_blink"
  "_box\"><property name=\"visible\">True</property><property name=\"sensi"
  "tive\">False</property><property name=\"left_padding\">12</property><ch"
  "ild><widget class=\"GtkVBox\" id=\"vbox7\"><property name=\"visible\">T"
  "rue</property><property name=\"spacing\">6</property><child><widget cla"
  "ss=\"GtkLabel\" id=\"label13\"><property name=\"visible\">True</propert"
  "y><property name=\"xalign\">0</property><property name=\"label\" transl"
  "atable=\"yes\">Blink _delay:</property><property name=\"use_underline\""
  ">True</property><property name=\"mnemonic_widget\">net_cursor_blink_tim"
  "e_scale</property></widget><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">False</property></packing></child><child"
  "><widget class=\"GtkHScale\" id=\"net_cursor_blink_time_scale\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"tooltip\" translatable=\"yes\">The length of t"
  "he cursor blink cycle in milliseconds</property><property name=\"update"
  "_policy\">GTK_UPDATE_DELAYED</property><property name=\"adjustment\">10"
  "00 100 2000 1 10 1</property><property name=\"digits\">0</property><pro"
  "perty name=\"value_pos\">GTK_POS_RIGHT</property></widget><packing><pro"
  "perty name=\"position\">1</property></packing></child></widget></child>"
  "</widget><packing><property name=\"expand\">False</property><property n"
  "ame=\"position\">1</property></packing></child></widget></child></widge"
  "t></child><child><widget class=\"GtkLabel\" id=\"label6\"><property nam"
  "e=\"visible\">True</property><property name=\"label\" translatable=\"ye"
  "s\">&lt;b&gt;Cursor&lt;/b&gt;</property><property name=\"use_markup\">T"
  "rue</property></widget><packing><property name=\"type\">label_item</pro"
  "perty></packing></child></widget><packing><property name=\"position\">1"
  "</property></packing></child></widget></child><child><widget class=\"Gt"
  "kHSeparator\" id=\"hseparator1\"><property name=\"visible\">True</prope"
  "rty></widget><packing><property name=\"expand\">False</property><proper"
  "ty name=\"padding\">6</property><property name=\"position\">1</property"
  "></packing></child><child><widget class=\"GtkLabel\" id=\"label1\"><pro"
  "perty name=\"visible\">True</property><property name=\"xalign\">0</prop"
  "erty><property name=\"yalign\">1</property><property name=\"label\" tra"
  "nslatable=\"yes\">Use this area to test the settings above:</property><"
  "property name=\"wrap_mode\">PANGO_WRAP_WORD_CHAR</property></widget><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">2</property></packing></ch"
  "ild><child><widget class=\"GtkEntry\" id=\"entry1\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property></wi"
  "dget><packing><property name=\"expand\">False</property><property name="
  "\"fill\">False</property><property name=\"position\">3</property></pack"
  "ing></child></widget></child><child><widget class=\"GtkLabel\" id=\"lab"
  "el2\"><property name=\"visible\">True</property><property name=\"label\""
  " translatable=\"yes\">Behavior</property></widget><packing><property na"
  "me=\"type\">tab</property><property name=\"tab_fill\">False</property><"
  "/packing></child><child><widget class=\"GtkFrame\" id=\"frame1\"><prope"
  "rty name=\"visible\">True</property><property name=\"border_width\">12<"
  "/property><property name=\"label_xalign\">0</property><property name=\""
  "shadow_type\">GTK_SHADOW_NONE</property><child><widget class=\"GtkAlign"
  "ment\" id=\"alignment6\"><property name=\"visible\">True</property><pro"
  "perty name=\"top_padding\">6</property><property name=\"bottom_padding\""
  ">6</property><property name=\"left_padding\">12</property><child><widge"
  "t class=\"GtkVBox\" id=\"vbox5\"><property name=\"visible\">True</prope"
  "rty><property name=\"spacing\">6</property><child><widget class=\"GtkLa"
  "bel\" id=\"label16\"><property name=\"visible\">True</property><propert"
  "y name=\"xalign\">0</property><property name=\"label\" translatable=\"y"
  "es\">Define shortcuts for launching applications:</property></widget><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property></packing></child><child><widget class=\"GtkScrolledWi"
  "ndow\" id=\"scrolledwindow2\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"hscrollba"
  "r_policy\">GTK_POLICY_AUTOMATIC</property><property name=\"vscrollbar_p"
  "olicy\">GTK_POLICY_AUTOMATIC</property><property name=\"shadow_type\">G"
  "TK_SHADOW_IN</property><child><widget class=\"GtkTreeView\" id=\"kbd_sh"
  "ortcuts_view\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"search_column\">0</prope"
  "rty></widget></child></widget><packing><property name=\"position\">1</p"
  "roperty></packing></child><child><widget class=\"GtkHButtonBox\" id=\"h"
  "buttonbox1\"><property name=\"visible\">True</property><property name=\""
  "border_width\">2</property><property name=\"spacing\">12</property><pro"
  "perty name=\"layout_style\">GTK_BUTTONBOX_SPREAD</property><child><widg"
  "et class=\"GtkButton\" id=\"add_shortcut_button\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"receives_default\">True</property><property name=\"label\" t"
  "ranslatable=\"yes\">gtk-add</property><property name=\"use_stock\">True"
  "</property><property name=\"response_id\">0</property></widget></child>"
  "<child><widget class=\"GtkButton\" id=\"delete_shortcut_button\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">True</property><property n"
  "ame=\"label\" translatable=\"yes\">gtk-remove</property><property name="
  "\"use_stock\">True</property><property name=\"response_id\">0</property"
  "></widget><packing><property name=\"position\">1</property></packing></"
  "child><child><widget class=\"GtkButton\" id=\"reset_shortcuts_button\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "True</property><property name=\"receives_default\">True</property><prop"
  "erty name=\"label\" translatable=\"yes\">_Reset to Defaults</property><"
  "property name=\"use_underline\">True</property><property name=\"respons"
  "e_id\">0</property></widget><packing><property name=\"position\">2</pro"
  "perty></packing></child></widget><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">False</property><property name=\"p"
  "osition\">2</property></packing></child></widget></child></widget></chi"
  "ld><child><widget class=\"GtkLabel\" id=\"label12\"><property name=\"vi"
  "sible\">True</property><property name=\"label\" translatable=\"yes\">&l"
  "t;b&gt;Application Shortcuts&lt;/b&gt;</property><property name=\"use_m"
  "arkup\">True</property></widget><packing><property name=\"type\">label_"
  "item</property></packing></child></widget><packing><property name=\"pos"
  "ition\">1</property></packing></child><child><widget class=\"GtkLabel\""
  " id=\"label3\"><property name=\"visible\">True</property><property name"
  "=\"label\" translatable=\"yes\">Application Shortcuts</property></widge"
  "t><packing><property name=\"type\">tab</property><property name=\"posit"
  "ion\">1</property><property name=\"tab_fill\">False</property></packing"
  "></child><child><widget class=\"GtkVBox\" id=\"xkb_tab_layout_vbox\"><p"
  "roperty name=\"border_width\">12</property><child><widget class=\"GtkFr"
  "ame\" id=\"frame5\"><property name=\"visible\">True</property><property"
  " name=\"label_xalign\">0</property><property name=\"shadow_type\">GTK_S"
  "HADOW_NONE</property><child><widget class=\"GtkAlignment\" id=\"alignme"
  "nt5\"><property name=\"visible\">True</property><property name=\"top_pa"
  "dding\">6</property><property name=\"bottom_padding\">6</property><prop"
  "erty name=\"left_padding\">12</property><child><widget class=\"GtkCheck"
  "Button\" id=\"xkb_use_system_default_checkbutton\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">True</property><prop"
  "erty name=\"label\" translatable=\"yes\">_Use system defaults</property"
  "><property name=\"use_underline\">True</property><property name=\"respo"
  "nse_id\">0</property><property name=\"draw_indicator\">True</property><"
  "/widget></child></widget></child><child><widget class=\"GtkLabel\" id=\""
  "label9\"><property name=\"visible\">True</property><property name=\"lab"
  "el\" translatable=\"yes\">&lt;b&gt;Keyboard settings&lt;/b&gt;</propert"
  "y><property name=\"use_markup\">True</property></widget><packing><prope"
  "rty name=\"type\">label_item</property></packing></child></widget><pack"
  "ing><property name=\"expand\">False</property></packing></child><child>"
  "<widget class=\"GtkFrame\" id=\"xkb_model_frame\"><property name=\"visi"
  "ble\">True</property><property name=\"label_xalign\">0</property><prope"
  "rty name=\"shadow_type\">GTK_SHADOW_NONE</property><child><widget class"
  "=\"GtkAlignment\" id=\"alignment1\"><property name=\"visible\">True</pr"
  "operty><property name=\"bottom_padding\">6</property><property name=\"l"
  "eft_padding\">12</property><child><widget class=\"GtkVBox\" id=\"vbox8\""
  "><property name=\"visible\">True</property><property name=\"border_widt"
  "h\">6</property><property name=\"spacing\">6</property><child><widget c"
  "lass=\"GtkComboBox\" id=\"xkb_model_combo\"><property name=\"visible\">"
  "True</property></widget></child></widget></child></widget></child><chil"
  "d><widget class=\"GtkLabel\" id=\"label11\"><property name=\"visible\">"
  "True</property><property name=\"label\" translatable=\"yes\">&lt;b&gt;K"
  "eyboard model&lt;/b&gt;</property><property name=\"use_markup\">True</p"
  "roperty></widget><packing><property name=\"type\">label_item</property>"
  "</packing></child></widget><packing><property name=\"expand\">False</pr"
  "operty><property name=\"position\">1</property></packing></child><child"
  "><widget class=\"GtkFrame\" id=\"xkb_layout_frame\"><property name=\"vi"
  "sible\">True</property><property name=\"label_xalign\">0</property><pro"
  "perty name=\"shadow_type\">GTK_SHADOW_NONE</property><child><widget cla"
  "ss=\"GtkAlignment\" id=\"alignment4\"><property name=\"visible\">True</"
  "property><property name=\"bottom_padding\">6</property><property name=\""
  "left_padding\">12</property><child><widget class=\"GtkVBox\" id=\"vbox9"
  "\"><property name=\"visible\">True</property><property name=\"border_wi"
  "dth\">6</property><property name=\"spacing\">6</property><child><widget"
  " class=\"GtkHBox\" id=\"hbox1\"><property name=\"visible\">True</proper"
  "ty><property name=\"spacing\">12</property><child><widget class=\"GtkSc"
  "rolledWindow\" id=\"scrolledwindow1\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"h"
  "scrollbar_policy\">GTK_POLICY_AUTOMATIC</property><property name=\"vscr"
  "ollbar_policy\">GTK_POLICY_AUTOMATIC</property><property name=\"shadow_"
  "type\">GTK_SHADOW_IN</property><child><widget class=\"GtkTreeView\" id="
  "\"xkb_layout_view\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">True</property><property name=\"search_column\">0</"
  "property></widget></child></widget></child><child><widget class=\"GtkVB"
  "ox\" id=\"vbox10\"><property name=\"visible\">True</property><property "
  "name=\"spacing\">6</property><child><widget class=\"GtkButton\" id=\"xk"
  "b_layout_add_button\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"receives_default\""
  ">True</property><property name=\"label\" translatable=\"yes\">gtk-add</"
  "property><property name=\"use_stock\">True</property><property name=\"r"
  "esponse_id\">0</property></widget><packing><property name=\"expand\">Fa"
  "lse</property></packing></child><child><widget class=\"GtkButton\" id=\""
  "xkb_layout_edit_button\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">True</property><property name=\"receives_defau"
  "lt\">True</property><property name=\"label\" translatable=\"yes\">gtk-e"
  "dit</property><property name=\"use_stock\">True</property><property nam"
  "e=\"response_id\">0</property></widget><packing><property name=\"expand"
  "\">False</property><property name=\"position\">1</property></packing></"
  "child><child><widget class=\"GtkButton\" id=\"xkb_layout_delete_button\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">True</property><pro"
  "perty name=\"label\" translatable=\"yes\">gtk-delete</property><propert"
  "y name=\"use_stock\">True</property><property name=\"response_id\">0</p"
  "roperty></widget><packing><property name=\"expand\">False</property><pr"
  "operty name=\"position\">2</property></packing></child></widget><packin"
  "g><property name=\"expand\">False</property><property name=\"position\""
  ">1</property></packing></child></widget></child></widget></child></widg"
  "et></child><child><widget class=\"GtkLabel\" id=\"label8\"><property na"
  "me=\"visible\">True</property><property name=\"label\" translatable=\"y"
  "es\">&lt;b&gt;Keyboard layout&lt;/b&gt;</property><property name=\"use_"
  "markup\">True</property></widget><packing><property name=\"type\">label"
  "_item</property></packing></child></widget><packing><property name=\"po"
  "sition\">2</property></packing></child></widget><packing><property name"
  "=\"position\">2</property></packing></child><child><widget class=\"GtkL"
  "abel\" id=\"label4\"><property name=\"visible\">True</property><propert"
  "y name=\"label\" translatable=\"yes\">Layout</property></widget><packin"
  "g><property name=\"type\">tab</property><property name=\"position\">2</"
  "property><property name=\"tab_fill\">False</property></packing></child>"
  "</widget><packing><property name=\"position\">1</property></packing></c"
  "hild></widget><packing><property name=\"position\">1</property></packin"
  "g></child><child internal-child=\"action_area\"><widget class=\"GtkHBut"
  "tonBox\" id=\"dialog-action_area1\"><property name=\"visible\">True</pr"
  "operty><property name=\"layout_style\">GTK_BUTTONBOX_EDGE</property><ch"
  "ild><widget class=\"GtkButton\" id=\"button1\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><property"
  " name=\"receives_default\">True</property><property name=\"label\" tran"
  "slatable=\"yes\">gtk-help</property><property name=\"use_stock\">True</"
  "property><property name=\"response_id\">0</property></widget></child><c"
  "hild><widget class=\"GtkButton\" id=\"button2\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">True</property><propert"
  "y name=\"receives_default\">True</property><property name=\"label\" tra"
  "nslatable=\"yes\">gtk-close</property><property name=\"use_stock\">True"
  "</property><property name=\"response_id\">0</property></widget><packing"
  "><property name=\"position\">1</property></packing></child></widget><pa"
  "cking><property name=\"expand\">False</property><property name=\"pack_t"
  "ype\">GTK_PACK_END</property></packing></child></widget></child></widge"
  "t><widget class=\"XfceTitledDialog\" id=\"keyboard-layout-selection-dia"
  "log\"><property name=\"title\" translatable=\"yes\">Keyboard layout sel"
  "ection</property><property name=\"window_position\">GTK_WIN_POS_CENTER_"
  "ON_PARENT</property><property name=\"default_height\">300</property><pr"
  "operty name=\"icon_name\">preferences-desktop-keyboard</property><prope"
  "rty name=\"type_hint\">GDK_WINDOW_TYPE_HINT_DIALOG</property><property "
  "name=\"has_separator\">False</property><property name=\"subtitle\" tran"
  "slatable=\"yes\">Keyboard layout and variant</property><child internal-"
  "child=\"vbox\"><widget class=\"GtkVBox\" id=\"dialog-vbox2\"><property "
  "name=\"visible\">True</property><property name=\"spacing\">2</property>"
  "<child><widget class=\"GtkScrolledWindow\" id=\"scrolledwindow3\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"border_width\">6</property><property name=\""
  "hscrollbar_policy\">GTK_POLICY_AUTOMATIC</property><property name=\"vsc"
  "rollbar_policy\">GTK_POLICY_AUTOMATIC</property><property name=\"shadow"
  "_type\">GTK_SHADOW_IN</property><child><widget class=\"GtkTreeView\" id"
  "=\"layout_selection_view\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"headers_visi"
  "ble\">False</property><property name=\"search_column\">0</property></wi"
  "dget></child></widget><packing><property name=\"position\">1</property>"
  "</packing></child><child internal-child=\"action_area\"><widget class=\""
  "GtkHButtonBox\" id=\"dialog-action_area2\"><property name=\"visible\">T"
  "rue</property><property name=\"layout_style\">GTK_BUTTONBOX_END</proper"
  "ty><child><widget class=\"GtkButton\" id=\"layout_selection_ok_button\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">True</property><pro"
  "perty name=\"label\" translatable=\"yes\">gtk-ok</property><property na"
  "me=\"use_stock\">True</property><property name=\"response_id\">1</prope"
  "rty></widget></child><child><widget class=\"GtkButton\" id=\"layout_sel"
  "ection_cancel_button\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"receives_default"
  "\">True</property><property name=\"label\" translatable=\"yes\">gtk-can"
  "cel</property><property name=\"use_stock\">True</property><property nam"
  "e=\"response_id\">0</property></widget><packing><property name=\"positi"
  "on\">1</property></packing></child></widget><packing><property name=\"e"
  "xpand\">False</property><property name=\"pack_type\">GTK_PACK_END</prop"
  "erty></packing></child></widget></child></widget></glade-interface>"
};

static const unsigned keyboard_dialog_glade_length = 22708u;

