#!/bin/sh
#
#
# Copyright (c) 2005-2006 Benedikt Meurer <benny@xfce.org>
#
# Opens the "Preferred Applications" dialog, which
# allows users to configure their preferred Web
# Browser, Mail Reader and Terminal Emulator.
#

exec /usr/lib/x86_64-linux-gnu/xfce4/exo-2/exo-helper-2 --configure "$@"
